services:
  - type: web
    name: caffeine-store
    env: node
    buildCommand: cd main && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd main && npm start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
