services:
  - type: web
    name: caveen-store
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caveen-db
          property: connectionString
      - key: NODE_ENV
        value: production
