services:
  - type: web
    name: caffeine-store
    runtime: node
    buildCommand: ./render-build.sh
    startCommand: node server.js
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: caffeine-db
          property: connectionString
