services:
  - type: web
    name: caffeine-store
    env: node
    buildCommand: |
      npm install
      npm run migrate
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://yousu7777_user:jrmM3IU3eTNWFzV1aoYBbx6KYWv1YnAc@dpg-d2fjjfggjchc73fobds0-a/yousu7777
      - key: DB_SSL
        value: "true"
    healthCheckPath: /health
    autoDeploy: yes

  - type: postgres
    name: caffeine-store-db
    plan: free
    databaseName: caffeine_store
    user: caffeine_user
    initSQLCommands:
      - |
        CREATE TABLE IF NOT EXISTS products (
          id SERIAL PRIMARY KEY,
          code VARCHAR(50) UNIQUE NOT NULL,
          category VARCHAR(50) NOT NULL,
          title VARCHAR(255) NOT NULL,
          price VARCHAR(50) NOT NULL,
          description TEXT,
          image_url VARCHAR(255)
        );
        ALTER TABLE products ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT 'Untitled Product';
        ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT 'Uncategorized';
